# Generated by Django 4.0.3 on 2022-04-27 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.URLField(default='', max_length=500)),
                ('is_link_to_book', models.BooleanField(default=False)),
                ('is_link_to_command', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('task_file_id', models.CharField(default='', max_length=1000)),
                ('task_text', models.CharField(default='', max_length=5000)),
                ('task_photo_id', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InternalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=2000)),
                ('file_id', models.CharField(default='', max_length=1000)),
                ('photo_id', models.CharField(default='', max_length=1000)),
                ('text', models.CharField(default='', max_length=5000)),
                ('is_requirement', models.BooleanField(default=False)),
                ('is_homework', models.BooleanField(default=False)),
                ('is_solution', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('text', models.CharField(default='', max_length=5000)),
                ('photo_id', models.CharField(default='', max_length=1000)),
                ('file_id', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Пн', 'Monday'), ('Вт', 'Tuesday'), ('Ср', 'Wednsday'), ('Чт', 'Thursday'), ('Пт', 'Friday'), ('Сб', 'Saturday')], max_length=2)),
                ('time', models.CharField(choices=[('8:30', 'First'), ('10:10', 'Second'), ('11:50', 'Third'), ('13:50', 'Fourth'), ('15:30', 'Fifth'), ('17:10', 'Sixth'), ('18:50', 'Seventh'), ('+', 'Eighth')], default='', max_length=5)),
                ('lesson', models.CharField(default='', max_length=200)),
                ('group', models.CharField(default='', max_length=200)),
                ('teacher', models.CharField(default='', max_length=200)),
                ('isOnline', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('file_id', models.CharField(default='', max_length=1000)),
                ('photo_id', models.CharField(default='', max_length=500)),
                ('text', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language_code',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='requirementfile',
            name='requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.requirements'),
        ),
    ]
