# Generated by Django 4.0.3 on 2022-03-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_code',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
