# Generated by Django 4.0.3 on 2022-04-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_externalresource_homework_internalresource_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.RemoveField(
            model_name='requirementfile',
            name='requirements',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='RequirementFile',
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
    ]
