# Generated by Django 4.0.3 on 2022-04-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_delete_homework_remove_requirementfile_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='file_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='schedule',
            name='photo_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
