# Generated by Django 4.0.3 on 2022-03-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='message',
            new_name='day',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons', models.CharField(max_length=20)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.day')),
            ],
        ),
    ]
