# Generated by Django 4.0.3 on 2022-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_schedule_file_id_schedule_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Пн', 'Monday'), ('Вт', 'Tuesday'), ('Ср', 'Wednsday'), ('Чт', 'Thursday'), ('Пт', 'Friday'), ('Сб', 'Saturday')], default='', max_length=2),
        ),
    ]
