# Generated by Django 4.0.3 on 2022-03-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_rename_message_day_day_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
