# Generated by Django 4.0.3 on 2022-04-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_schedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='externalresource',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='internalresource',
            name='category',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='internalresource',
            name='is_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InternalResourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(default='', max_length=500)),
                ('file_id', models.CharField(default='', max_length=500)),
                ('internal_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.internalresource')),
            ],
        ),
    ]
