# Generated by Django 4.0.3 on 2022-03-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_remove_schedule_day_delete_day_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Пн', 'Monday'), ('Вт', 'Tuesday'), ('Ср', 'Wednsday'), ('Чт', 'Thursday'), ('Пт', 'Friday'), ('Сб', 'Saturday')], max_length=2)),
                ('time', models.CharField(choices=[('8:30', 'First'), ('10:10', 'Second'), ('11:50', 'Third'), ('13:50', 'Fourth'), ('15:30', 'Fifth'), ('17:10', 'Sixth'), ('18:50', 'Seventh'), ('20:30', 'Eighth')], max_length=5)),
                ('lesson', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
