# Generated by Django 4.0.3 on 2022-04-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_remove_schedule_file_id_remove_schedule_photo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalresource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='internalresource',
            name='category',
        ),
    ]
