# Generated by Django 4.0.3 on 2022-03-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=300)),
                ('lesson', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(choices=[('8:30', 'First'), ('10:10', 'Second'), ('11:50', 'Third'), ('13:50', 'Fourth'), ('15:30', 'Fifth'), ('17:10', 'Sixth'), ('18:50', 'Seventh'), ('20:30', 'Eighth')], default='', max_length=5),
        ),
    ]
