# Generated by Django 4.0.3 on 2022-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_links_schedule_group_schedule_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isOnline',
            field=models.CharField(default='', max_length=200),
        ),
    ]
