# Generated by Django 4.0.3 on 2022-05-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_remove_internalresource_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalresourcefile',
            name='internal_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.internalresource'),
        ),
    ]
