# Generated by Django 4.0.3 on 2022-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_schedule_isonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(),
        ),
    ]
