# Generated by Django 4.0.3 on 2022-03-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_alter_links_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='link',
        ),
        migrations.AddField(
            model_name='links',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
