# Generated by Django 4.0.3 on 2022-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_remove_links_link_links_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
