# Generated by Django 4.0.3 on 2022-04-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0016_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='task',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
