# Generated by Django 4.0.3 on 2022-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0017_homework_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='task_file',
            field=models.FileField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
