# Generated by Django 4.0.3 on 2022-04-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0018_alter_homework_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%D/'),
        ),
    ]
