# Generated by Django 4.0.3 on 2022-04-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0019_alter_homework_name_alter_homework_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='test',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
