# Generated by Django 4.0.3 on 2022-04-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0020_homework_test_alter_homework_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='task_file',
        ),
    ]
