# Generated by Django 4.0.3 on 2022-04-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0021_remove_homework_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
