# Generated by Django 4.0.3 on 2022-04-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0022_homework_task_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
