# Generated by Django 4.0.3 on 2022-04-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0024_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='task_file',
        ),
        migrations.AddField(
            model_name='homework',
            name='task_doc',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
