# Generated by Django 4.0.3 on 2022-04-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0026_alter_homework_task_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='task_doc',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
