# Generated by Django 4.0.3 on 2022-04-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0028_alter_homework_task_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homework',
            name='task',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_doc',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
