# Generated by Django 4.0.3 on 2022-04-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0030_rename_task_homework_task_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='task_photo_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
