# Generated by Django 4.0.3 on 2022-04-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0031_homework_task_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('file_field', models.FileField(default=None, null=True, upload_to='')),
                ('photo_id', models.CharField(default='', max_length=500)),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
