# Generated by Django 4.0.3 on 2022-04-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0032_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirements',
            old_name='requirement',
            new_name='text',
        ),
    ]
