# Generated by Django 4.0.3 on 2022-04-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0033_rename_requirement_requirements_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(default=None, null=True, upload_to='')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.requirements')),
            ],
        ),
    ]
