# Generated by Django 4.0.3 on 2022-04-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0034_requirementfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='file_field',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='books',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
