# Generated by Django 4.0.3 on 2022-04-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0035_books_file_field_books_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='file_field',
        ),
        migrations.RemoveField(
            model_name='books',
            name='text',
        ),
    ]
