# Generated by Django 4.0.3 on 2022-04-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0036_remove_books_file_field_remove_books_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='photo_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
