# Generated by Django 4.0.3 on 2022-04-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0037_requirements_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(choices=[('8:30', 'First'), ('10:10', 'Second'), ('11:50', 'Third'), ('13:50', 'Fourth'), ('15:30', 'Fifth'), ('17:10', 'Sixth'), ('18:50', 'Seventh'), ('+', 'Eighth')], default='', max_length=5),
        ),
    ]
