# Generated by Django 4.0.3 on 2022-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0038_alter_schedule_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='task_doc',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='file_field',
        ),
        migrations.AddField(
            model_name='homework',
            name='task_file_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='requirements',
            name='file_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='solution',
            name='file_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_photo_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='photo_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='solution',
            name='text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
