add_or_delete_text = "Добавить или удалить книгу?"
no_books_yet_text = "Пока нет книг"
put_book_name_text = "Введите название новой книги"
choose_book_to_delete_text = "Выберите номер книги для удаления"
nothing_to_delete_text = "Пока удалять нечего"
put_book_url = "Вставьте ссылку на книгу(гугл-диск, яндекс-диск, облако...)"
url_is_added_text = "Новая книга добавлена"
successful_del_text = "Книга успешно удалена"
number_requested_text = "Нужно число, а не буковы"
cancel_delete_text = "Отменить удаление книги"
url_requested_text = "Нужна ссылка"

DELETE_BOOK_BUTTON = "Удалить книгу"
ADD_BOOK_BUTTON = "Добавить книгу"
CANCEL_DELETE_BUTTON = "Отменить удаление книги"